# (실습) 어레이 중심 프로그래밍

**주의사항**

- `None`은 적절한 표현식으로 대체한다.
- `Pass`는 적절한 명령문으로 대체한다.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

**문제 1**

길이가 같은 두 개의 랜덤 벡터 `A`, `B`가 다음과 같이 주어졌다.

In [2]:
A = np.random.randint(0,2,5)
A

array([1, 1, 1, 1, 0])

In [3]:
B = np.random.randint(0,2,5)
B

array([1, 1, 1, 0, 1])

(1) 두 벡터의 모든 항목이 동일한지 여부를 판단하라.
단, `all()` 메서드를 이용한다.

In [ ]:
Z = (A == B).all()

False


아래 코드는 수정하지 마세요!!!

In [5]:
Y = ((A==B).sum() == len(A))
assert Z == Y

(2) 최소 한 개 이상의 항목이 동일한 인덱스에 위치하는지 여부를 판단하라.
단, `any()` 메서드를 이용한다.

In [7]:
Z = (A == B).any()

아래 코드는 수정하지 마세요!!!

In [8]:
Y = ((A==B).sum() > 0)
assert Z == Y

**문제 2**

`np.random.rand()` 함수는 `[0, 1)` 구간에서 균등 분포를
따르는 부동소수점을 무작위로 선택하여 지정된 모양의 어레이를 생성한다.

In [130]:
np.random.seed(10)

Z = np.random.rand(10, 2)
Z

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981],
       [0.68535982, 0.95339335],
       [0.00394827, 0.51219226],
       [0.81262096, 0.61252607],
       [0.72175532, 0.29187607],
       [0.91777412, 0.71457578]])

변수 `Z`가 가리키는 벡터의 항목 중에서 열별 최댓값을 -1로 대체하라.

힌트: `max()` 어레이 메서드, 부울 인덱싱

In [139]:
mask = Z >= Z.max(axis=0)
print(mask)
Z[mask] = -1
Z

[[False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False  True]
 [False False]
 [False False]
 [False False]
 [ True False]]


array([[ 0.77132064,  0.02075195],
       [ 0.63364823,  0.74880388],
       [ 0.49850701,  0.22479665],
       [ 0.19806286,  0.76053071],
       [ 0.16911084,  0.08833981],
       [ 0.68535982, -1.        ],
       [ 0.00394827,  0.51219226],
       [ 0.81262096,  0.61252607],
       [ 0.72175532,  0.29187607],
       [-1.        ,  0.71457578]])

아래 코드는 수정하지 마세요!!!

In [140]:
assert (Z.min(axis=0)==-1).all()

**문제 3**

`np.random.uniform()` 함수는 지정된 구간에서 지정된 개수의 부동소수점을 균등 분포를 따르면서 무작위로 선택해서
1차원 어레이를 생성한다.

In [154]:
np.random.seed(10)

Z = np.random.uniform(0, 1, 10)
Z

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

변수 `Z`가 가리키는 어레이에 포함된 항목 중에서 항목들의 평균값에 가장 가까운 값을
`min_mean` 변수가 가리키도록 하라.
단, `argimin()` 메서드와 `np.abs()` 함수를 이용한다.

In [155]:
min_mean = Z[(np.abs(0.5-Z)).argmin()]
print(min_mean)

0.4985070123025904


아래 코드는 수정하지 마세요!!!

In [156]:
assert round(min_mean, 3) == 0.499

**문제 4**

2차원 어레이가 다음가 같이 주어졌다.

In [172]:
Z = np.random.rand(10, 2)
Z

array([[0.03995921, 0.42949218],
       [0.31492687, 0.63649114],
       [0.34634715, 0.04309736],
       [0.87991517, 0.76324059],
       [0.87809664, 0.41750914],
       [0.60557756, 0.51346663],
       [0.59783665, 0.26221566],
       [0.30087131, 0.02539978],
       [0.30306256, 0.24207588],
       [0.55757819, 0.56550702]])

변수 `Z`가 가리키는 어레이를 정규화 하라.
즉, 항목들의 평균은 0, 표준편차는 1이 되도록 한다.
단, `mean()`과 `std()` 메서드를 이용한다.

In [175]:
Z= (Z - Z.mean())/Z.std()
Z

array([[-1.59176143, -0.02668306],
       [-0.48698731,  0.80500419],
       [-0.36074588, -1.57915288],
       [ 1.78304127,  1.31426227],
       [ 1.77573471, -0.07482889],
       [ 0.6807986 ,  0.31071225],
       [ 0.64969689, -0.69877215],
       [-0.54346021, -1.65025877],
       [-0.53465613, -0.77969044],
       [ 0.48794513,  0.51980185]])

아래 코드는 수정하지 마세요!!!

In [176]:
assert round(Z.mean(), 1) == 0.0
assert round(Z.std(), 1) == 1.0

**텍스트 파일 다운로드 후 활용**

`data_path`가 가리키는 인터넷 주소에 아래 내용의 파일이 저장되어 있다.

```python
1,  2,  3,  4,  5
6,  7,  8,  9, 10
11, 12, 13, 14, 15
```

In [ ]:
data_path = "https://raw.githubusercontent.com/codingalzi/datapy/master/practices/data/exc_data_import.txt"

**문제 5**

위 파일을 불러와 아래 모양의 2차원 어레이를 생성하라.

힌트: `np.genfromtxt()` 함수와 `delimiter` 키워드 매개변수

```python
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])
```

In [190]:
Z = np.genfromtxt('practice_numpu_3_2.txt',delimiter=',')
Z

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.]])

아래 코드는 수정하지 마세요!!!

In [191]:
assert (Z == np.array([[ 1,  2,  3,  4,  5],
                        [ 6,  7,  8,  9, 10],
                        [11, 12, 13, 14, 15]])).all()

**문제 6**

`Z`에 `np.divmod()` 함수를 적용하라. 단 7로 나눈 몫과 나머지로 이루어진 어레이를 생성해야 한다.

In [193]:
Zmod = np.divmod(Z,7)
Zmod

(array([[0., 0., 0., 0., 0.],
        [0., 1., 1., 1., 1.],
        [1., 1., 1., 2., 2.]]),
 array([[1., 2., 3., 4., 5.],
        [6., 0., 1., 2., 3.],
        [4., 5., 6., 0., 1.]]))

아래 코드는 수정하지 마세요!!!

In [194]:
assert (Zmod[0] == np.array([[0, 0, 0, 0, 0],
                              [0, 1, 1, 1, 1],
                              [1, 1, 1, 2, 2]])).all()

assert (Zmod[1] == np.array([[1, 2, 3, 4, 5],
                              [6, 0, 1, 2, 3],
                              [4, 5, 6, 0, 1]])).all()

**문제 7**

변수 `Z`가 가리키는 어레이에 7로 나누어 떨어지는 항목의 수를 `n_mod7_0` 변수가 가리키도록 하라.
단, `Zmod`와 `sum()` 메서드를 이용한다.

In [ ]:
n_mod7_0 = sum()
n_mod7_0

array([1., 2., 2., 3., 3.])

아래 코드는 수정하지 마세요!!!

In [ ]:
assert n_mod7_0 == 2

**문제 8**

변수 `Z`가 가리키는 어레이에 7로 나눴을 때 나머지가 3인 항목만으로 이루어진 1차원 어레이를 `n_mod7_3` 변수가 가리키도록 하라.
단, `Zmod`와 부울 인덱싱을 활용한다.

In [ ]:
n_mod7_3 = None

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (n_mod7_3 == np.array([ 3, 10])).all()

**문제 9**

다음 어레이를 이용한다.

In [ ]:
np.random.seed(1235)

Z = np.random.randint(0,50,(4, 3))
Z

array([[11, 34,  2],
       [47,  3,  7],
       [35, 40, 16],
       [16,  2, 15]])

1번 열에 위치한 값들의 순서대로 행을 재배치한 어레이를 변수 `X`가 가리키도록 하라.
단, `argsort()` 메서드와 인덱싱, 슬라이싱, 팬시 인덱싱을 사용한다.

In [ ]:
X = None

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (X == np.array([[16,  2, 15],
                        [47,  3,  7],
                        [11, 34,  2],
                        [35, 40, 16]])).all()

**문제 10**

아래와 같은 그래프를 그리는 코드를 완성하라.
단, `np.sin()`, `np.cos()` 두 유니버설 함수를 이용한다.

<div align="center"><img src="https://raw.githubusercontent.com/codingalzi/datapy/master/jupyter-book/images/sine-cosine.png?raw=true" style="width:400px;"></div>

In [ ]:
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = None
y_cos = None

plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis')
plt.ylabel('y axis')
plt.legend(['sine', 'cosine'])

plt.show()